// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "pokemons",
    columns: [
      { name: "pkmName", type: "string" },
      { name: "pkmId", type: "string" },
      { name: "pkmImg", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Pokemons = InferredTypes["pokemons"];
export type PokemonsRecord = Pokemons & XataRecord;

export type DatabaseSchema = {
  pokemons: PokemonsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://demos-urucbe.eu-west-1.xata.sh/db/pokemon-trainer",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
